import ProjectDescription
import ProjectDescriptionHelpers

let virgoApp = Workspace(
    name: "Poke",
    projects: ["PokeApp"],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)